CONTROLLER_HEART_BEAT_EXPIRATION = 30
WORKER_HEART_BEAT_INTERVAL = 15

LOGDIR = "."

# Model Constants
IGNORE_INDEX = -100
IMAGE_TOKEN_INDEX = -200
DEFAULT_IMAGE_TOKEN = "<image>"
DEFAULT_IMAGE_PATCH_TOKEN = "<im_patch>"
DEFAULT_VQ_TOKEN_TEMPLATE_PREFIX = "<vq_token_"
DEFAULT_VQ_TOKEN_TEMPLATE = DEFAULT_VQ_TOKEN_TEMPLATE_PREFIX+"%d>"
DEFAULT_IM_START_TOKEN = "<im_start>"
DEFAULT_IM_END_TOKEN = "<im_end>"
IMAGE_PLACEHOLDER = "<image-placeholder>"
IMAGE_START_TOKEN_GEN = "<img>"
IMAGE_END_TOKEN_GEN = "</img>"
