from .configuration_xllmx_chameleon import ChameleonXLLMXConfig
from .modeling_xllmx_chameleon import ChameleonXLLMXForConditionalGeneration
# DEBUG/MODIFY Usage, to prevent hurt original code
from .modeling_xllmx_chameleon_base import ChameleonXLLMXForConditionalGenerationBase
from .modeling_xllmx_chameleon_anyres import ChameleonXLLMXForConditionalGenerationAnyRes 

from .modeling_gen_chameleon import ChameleonGenForConditionalGenerationBase


